---    
- name: Boot the system with an ISO
  hpilo_boot:
    host: "{{ iLo_IP }}"
    login: "{{ iLo_username }}"
    password: "{{ iLo_password }}"
    media: cdrom
    image: "{{ iso_image }}"
  delegate_to: localhost

- name: Power off the server
  hpilo_boot:
    host: "{{ iLo_IP }}"
    login: "{{ iLo_username }}"
    password: "{{ iLo_password }}"
    state: poweroff
  delegate_to: localhost
